message:
  channel: telegram
  ntfy:
    server: ""
    topic: ""
  telegram:
    token: ""
    chat_id: ""

debug: true
headless: false
execution_interval: 5000

#
pc_devices: "Desktop Edge"
pc_search_times: 33

phone_devices: "iPhone 15"
phone_search_times: 23

microsoft:
  user: ""
  password: ""
